/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::http::Client;

#[derive(Debug, Clone)]
pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: Client,
    pub basic_auth: Option<BasicAuth>,
    pub oauth_access_token: Option<String>,
    pub bearer_access_token: Option<String>,
    pub api_key: Option<ApiKey>,
}

pub type BasicAuth = (String, Option<String>);

#[derive(Debug, Clone)]
pub struct ApiKey {
    pub prefix: Option<String>,
    pub key: String,
}

impl Configuration {
    pub fn new() -> Configuration {
        Configuration::default()
    }
    pub fn testnet() -> Configuration {
        Configuration::default()
    }
    pub fn devnet() -> Configuration {
        Configuration {
            base_path: "https://api.devnet.aptoslabs.com/v1".to_owned(),
            ..Configuration::default()
        }
    }
    pub fn mainnet() -> Configuration {
        Configuration {
            base_path: "https://api.devnet.aptoslabs.com/v1".to_owned(),
            ..Configuration::default()
        }
    }
}

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: "https://api.testnet.aptoslabs.com/v1".to_owned(),
            user_agent: Some("OpenAPI-Generator/1.2.0/rust".to_owned()),
            client: Client {},
            basic_auth: None,
            oauth_access_token: None,
            bearer_access_token: None,
            api_key: None,
        }
    }
}
