/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountSignatureSingleKeySignature {
    #[serde(rename = "public_key")]
    pub public_key: Box<models::PublicKey>,
    #[serde(rename = "signature")]
    pub signature: Box<models::Signature>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AccountSignatureSingleKeySignature {
    pub fn new(public_key: models::PublicKey, signature: models::Signature, r#type: Type) -> AccountSignatureSingleKeySignature {
        AccountSignatureSingleKeySignature {
            public_key: Box::new(public_key),
            signature: Box::new(signature),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "single_key_signature")]
    SingleKeySignature,
}

impl Default for Type {
    fn default() -> Type {
        Self::SingleKeySignature
    }
}

