/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountSignature : Account signature scheme  The account signature scheme allows you to have two types of accounts:  1. A single Ed25519 key account, one private key 2. A k-of-n multi-Ed25519 key account, multiple private keys, such that k-of-n must sign a transaction. 3. A single Secp256k1Ecdsa key account, one private key
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AccountSignature {
    #[serde(rename="ed25519_signature")]
    Ed25519Signature(Box<models::AccountSignatureEd25519Signature>),
    #[serde(rename="multi_ed25519_signature")]
    MultiEd25519Signature(Box<models::AccountSignatureMultiEd25519Signature>),
    #[serde(rename="single_key_signature")]
    SingleKeySignature(Box<models::AccountSignatureSingleKeySignature>),
    #[serde(rename="multi_key_signature")]
    MultiKeySignature(Box<models::AccountSignatureMultiKeySignature>),
    #[serde(rename="no_account_signature")]
    NoAccountSignature(Box<models::AccountSignatureNoAccountSignature>),
}

impl Default for AccountSignature {
    fn default() -> Self {
        Self::Ed25519Signature(Default::default())
    }
}


