/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountData : Account data  A simplified version of the onchain Account resource
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountData {
    /// A string containing a 64-bit unsigned integer.  We represent u64 values as a string to ensure compatibility with languages such as JavaScript that do not parse u64s in JSON natively. 
    #[serde(rename = "sequence_number")]
    pub sequence_number: String,
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "authentication_key")]
    pub authentication_key: String,
}

impl AccountData {
    /// Account data  A simplified version of the onchain Account resource
    pub fn new(sequence_number: String, authentication_key: String) -> AccountData {
        AccountData {
            sequence_number,
            authentication_key,
        }
    }
}

