/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockMetadataExtensionBlockMetadataExtensionRandomness {
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "randomness", skip_serializing_if = "Option::is_none")]
    pub randomness: Option<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl BlockMetadataExtensionBlockMetadataExtensionRandomness {
    pub fn new(r#type: Type) -> BlockMetadataExtensionBlockMetadataExtensionRandomness {
        BlockMetadataExtensionBlockMetadataExtensionRandomness {
            randomness: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "v1")]
    V1,
}

impl Default for Type {
    fn default() -> Type {
        Self::V1
    }
}

