/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockEndInfo {
    #[serde(rename = "block_gas_limit_reached")]
    pub block_gas_limit_reached: bool,
    #[serde(rename = "block_output_limit_reached")]
    pub block_output_limit_reached: bool,
    #[serde(rename = "block_effective_block_gas_units")]
    pub block_effective_block_gas_units: i32,
    #[serde(rename = "block_approx_output_size")]
    pub block_approx_output_size: i32,
}

impl BlockEndInfo {
    pub fn new(block_gas_limit_reached: bool, block_output_limit_reached: bool, block_effective_block_gas_units: i32, block_approx_output_size: i32) -> BlockEndInfo {
        BlockEndInfo {
            block_gas_limit_reached,
            block_output_limit_reached,
            block_effective_block_gas_units,
            block_approx_output_size,
        }
    }
}

