/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum BlockMetadataExtension {
    #[serde(rename="v0")]
    V0(Box<models::BlockMetadataExtensionBlockMetadataExtensionEmpty>),
    #[serde(rename="v1")]
    V1(Box<models::BlockMetadataExtensionBlockMetadataExtensionRandomness>),
}

impl Default for BlockMetadataExtension {
    fn default() -> Self {
        Self::V0(Default::default())
    }
}


