/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DecodedTableData : Decoded table data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecodedTableData {
    /// Key of table in JSON
    #[serde(rename = "key", deserialize_with = "Option::deserialize")]
    pub key: Option<serde_json::Value>,
    /// Type of key
    #[serde(rename = "key_type")]
    pub key_type: String,
    /// Value of table in JSON
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<serde_json::Value>,
    /// Type of value
    #[serde(rename = "value_type")]
    pub value_type: String,
}

impl DecodedTableData {
    /// Decoded table data
    pub fn new(key: Option<serde_json::Value>, key_type: String, value: Option<serde_json::Value>, value_type: String) -> DecodedTableData {
        DecodedTableData {
            key,
            key_type,
            value,
            value_type,
        }
    }
}

