/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeletedTableData : Deleted table data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeletedTableData {
    /// Deleted key
    #[serde(rename = "key", deserialize_with = "Option::deserialize")]
    pub key: Option<serde_json::Value>,
    /// Deleted key type
    #[serde(rename = "key_type")]
    pub key_type: String,
}

impl DeletedTableData {
    /// Deleted table data
    pub fn new(key: Option<serde_json::Value>, key_type: String) -> DeletedTableData {
        DeletedTableData {
            key,
            key_type,
        }
    }
}

