/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectWriteSet {
    #[serde(rename = "changes")]
    pub changes: Vec<models::WriteSetChange>,
    #[serde(rename = "events")]
    pub events: Vec<models::Event>,
}

impl DirectWriteSet {
    pub fn new(changes: Vec<models::WriteSetChange>, events: Vec<models::Event>) -> DirectWriteSet {
        DirectWriteSet {
            changes,
            events,
        }
    }
}

