/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Ed25519Signature : A single Ed25519 signature
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ed25519Signature {
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "public_key")]
    pub public_key: String,
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "signature")]
    pub signature: String,
}

impl Ed25519Signature {
    /// A single Ed25519 signature
    pub fn new(public_key: String, signature: String) -> Ed25519Signature {
        Ed25519Signature {
            public_key,
            signature,
        }
    }
}

