/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExportedQuorumCertifiedUpdate : A more API-friendly representation of the on-chain `aptos_types::jwks::QuorumCertifiedUpdate`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportedQuorumCertifiedUpdate {
    #[serde(rename = "update")]
    pub update: Box<models::ExportedProviderJwks>,
    #[serde(rename = "multi_sig")]
    pub multi_sig: Box<models::ExportedAggregateSignature>,
}

impl ExportedQuorumCertifiedUpdate {
    /// A more API-friendly representation of the on-chain `aptos_types::jwks::QuorumCertifiedUpdate`.
    pub fn new(update: models::ExportedProviderJwks, multi_sig: models::ExportedAggregateSignature) -> ExportedQuorumCertifiedUpdate {
        ExportedQuorumCertifiedUpdate {
            update: Box::new(update),
            multi_sig: Box::new(multi_sig),
        }
    }
}

