/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExportedProviderJwks : A more API-friendly representation of the on-chain `aptos_types::jwks::ProviderJWKs`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportedProviderJwks {
    #[serde(rename = "issuer")]
    pub issuer: String,
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "jwks")]
    pub jwks: Vec<models::Jwk>,
}

impl ExportedProviderJwks {
    /// A more API-friendly representation of the on-chain `aptos_types::jwks::ProviderJWKs`.
    pub fn new(issuer: String, version: i32, jwks: Vec<models::Jwk>) -> ExportedProviderJwks {
        ExportedProviderJwks {
            issuer,
            version,
            jwks,
        }
    }
}

