/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenesisPayloadWriteSetPayload {
    #[serde(rename = "write_set")]
    pub write_set: Box<models::WriteSet>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl GenesisPayloadWriteSetPayload {
    pub fn new(write_set: models::WriteSet, r#type: Type) -> GenesisPayloadWriteSetPayload {
        GenesisPayloadWriteSetPayload {
            write_set: Box::new(write_set),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "write_set_payload")]
    WriteSetPayload,
}

impl Default for Type {
    fn default() -> Type {
        Self::WriteSetPayload
    }
}

