/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HealthCheckSuccess : Representation of a successful healthcheck
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthCheckSuccess {
    #[serde(rename = "message")]
    pub message: String,
}

impl HealthCheckSuccess {
    /// Representation of a successful healthcheck
    pub fn new(message: String) -> HealthCheckSuccess {
        HealthCheckSuccess {
            message,
        }
    }
}

