/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexedSignature {
    #[serde(rename = "index")]
    pub index: i32,
    #[serde(rename = "signature")]
    pub signature: Box<models::Signature>,
}

impl IndexedSignature {
    pub fn new(index: i32, signature: models::Signature) -> IndexedSignature {
        IndexedSignature {
            index,
            signature: Box::new(signature),
        }
    }
}

