/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Jwk : The JWK type that can be converted from/to `JWKMoveStruct` but easier to use in rust.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Jwk {
    #[serde(rename = "kid")]
    pub kid: String,
    #[serde(rename = "kty")]
    pub kty: String,
    #[serde(rename = "alg")]
    pub alg: String,
    #[serde(rename = "e")]
    pub e: String,
    #[serde(rename = "n")]
    pub n: String,
    #[serde(rename = "id")]
    pub id: Vec<i32>,
    #[serde(rename = "payload")]
    pub payload: Vec<i32>,
}

impl Jwk {
    /// The JWK type that can be converted from/to `JWKMoveStruct` but easier to use in rust.
    pub fn new(kid: String, kty: String, alg: String, e: String, n: String, id: Vec<i32>, payload: Vec<i32>) -> Jwk {
        Jwk {
            kid,
            kty,
            alg,
            e,
            n,
            id,
            payload,
        }
    }
}

