/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MoveValue : An enum of the possible Move value types
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoveValue {
}

impl MoveValue {
    /// An enum of the possible Move value types
    pub fn new() -> MoveValue {
        MoveValue {
        }
    }
}

