/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MoveFunctionGenericTypeParam : Move function generic type param
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoveFunctionGenericTypeParam {
    /// Move abilities tied to the generic type param and associated with the function that uses it
    #[serde(rename = "constraints")]
    pub constraints: Vec<String>,
}

impl MoveFunctionGenericTypeParam {
    /// Move function generic type param
    pub fn new(constraints: Vec<String>) -> MoveFunctionGenericTypeParam {
        MoveFunctionGenericTypeParam {
            constraints,
        }
    }
}

