/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MoveStructGenericTypeParam : Move generic type param
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoveStructGenericTypeParam {
    /// Move abilities tied to the generic type param and associated with the type that uses it
    #[serde(rename = "constraints")]
    pub constraints: Vec<String>,
}

impl MoveStructGenericTypeParam {
    /// Move generic type param
    pub fn new(constraints: Vec<String>) -> MoveStructGenericTypeParam {
        MoveStructGenericTypeParam {
            constraints,
        }
    }
}

