/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MoveScriptBytecode : Move script bytecode
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoveScriptBytecode {
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "bytecode")]
    pub bytecode: String,
    #[serde(rename = "abi", skip_serializing_if = "Option::is_none")]
    pub abi: Option<Box<models::MoveFunction>>,
}

impl MoveScriptBytecode {
    /// Move script bytecode
    pub fn new(bytecode: String) -> MoveScriptBytecode {
        MoveScriptBytecode {
            bytecode,
            abi: None,
        }
    }
}

