/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MultiKeySignature : A multi key signature
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiKeySignature {
    #[serde(rename = "public_keys")]
    pub public_keys: Vec<models::PublicKey>,
    #[serde(rename = "signatures")]
    pub signatures: Vec<models::IndexedSignature>,
    #[serde(rename = "signatures_required")]
    pub signatures_required: i32,
}

impl MultiKeySignature {
    /// A multi key signature
    pub fn new(public_keys: Vec<models::PublicKey>, signatures: Vec<models::IndexedSignature>, signatures_required: i32) -> MultiKeySignature {
        MultiKeySignature {
            public_keys,
            signatures,
            signatures_required,
        }
    }
}

