/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum MultisigTransactionPayload {
    #[serde(rename="entry_function_payload")]
    EntryFunctionPayload(Box<models::MultisigTransactionPayloadEntryFunctionPayload>),
}

impl Default for MultisigTransactionPayload {
    fn default() -> Self {
        Self::EntryFunctionPayload(Default::default())
    }
}


