/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoleType {
    #[serde(rename = "validator")]
    Validator,
    #[serde(rename = "full_node")]
    FullNode,

}

impl std::fmt::Display for RoleType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Validator => write!(f, "validator"),
            Self::FullNode => write!(f, "full_node"),
        }
    }
}

impl Default for RoleType {
    fn default() -> RoleType {
        Self::Validator
    }
}

