/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RsaJwk : Move type `0x1::jwks::RSA_JWK` in rust. See its doc in Move for more details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RsaJwk {
    #[serde(rename = "kid")]
    pub kid: String,
    #[serde(rename = "kty")]
    pub kty: String,
    #[serde(rename = "alg")]
    pub alg: String,
    #[serde(rename = "e")]
    pub e: String,
    #[serde(rename = "n")]
    pub n: String,
}

impl RsaJwk {
    /// Move type `0x1::jwks::RSA_JWK` in rust. See its doc in Move for more details.
    pub fn new(kid: String, kty: String, alg: String, e: String, n: String) -> RsaJwk {
        RsaJwk {
            kid,
            kty,
            alg,
            e,
            n,
        }
    }
}

