/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScriptWriteSet {
    /// A hex encoded 32 byte Aptos account address.  This is represented in a string as a 64 character hex string, sometimes shortened by stripping leading 0s, and adding a 0x.  For example, address 0x0000000000000000000000000000000000000000000000000000000000000001 is represented as 0x1. 
    #[serde(rename = "execute_as")]
    pub execute_as: String,
    #[serde(rename = "script")]
    pub script: Box<models::ScriptPayload>,
}

impl ScriptWriteSet {
    pub fn new(execute_as: String, script: models::ScriptPayload) -> ScriptWriteSet {
        ScriptWriteSet {
            execute_as,
            script: Box::new(script),
        }
    }
}

