/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScriptPayload : Payload which runs a script that can run multiple functions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScriptPayload {
    #[serde(rename = "code")]
    pub code: Box<models::MoveScriptBytecode>,
    /// Type arguments of the function
    #[serde(rename = "type_arguments")]
    pub type_arguments: Vec<String>,
    /// Arguments of the function
    #[serde(rename = "arguments")]
    pub arguments: Vec<serde_json::Value>,
}

impl ScriptPayload {
    /// Payload which runs a script that can run multiple functions
    pub fn new(code: models::MoveScriptBytecode, type_arguments: Vec<String>, arguments: Vec<serde_json::Value>) -> ScriptPayload {
        ScriptPayload {
            code: Box::new(code),
            type_arguments,
            arguments,
        }
    }
}

