/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SingleKeySignature : A single key signature
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SingleKeySignature {
    #[serde(rename = "public_key")]
    pub public_key: Box<models::PublicKey>,
    #[serde(rename = "signature")]
    pub signature: Box<models::Signature>,
}

impl SingleKeySignature {
    /// A single key signature
    pub fn new(public_key: models::PublicKey, signature: models::Signature) -> SingleKeySignature {
        SingleKeySignature {
            public_key: Box::new(public_key),
            signature: Box::new(signature),
        }
    }
}

