/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionSignatureMultiAgentSignature {
    #[serde(rename = "sender")]
    pub sender: Box<models::AccountSignature>,
    /// The other involved parties' addresses
    #[serde(rename = "secondary_signer_addresses")]
    pub secondary_signer_addresses: Vec<String>,
    /// The associated signatures, in the same order as the secondary addresses
    #[serde(rename = "secondary_signers")]
    pub secondary_signers: Vec<models::AccountSignature>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl TransactionSignatureMultiAgentSignature {
    pub fn new(sender: models::AccountSignature, secondary_signer_addresses: Vec<String>, secondary_signers: Vec<models::AccountSignature>, r#type: Type) -> TransactionSignatureMultiAgentSignature {
        TransactionSignatureMultiAgentSignature {
            sender: Box::new(sender),
            secondary_signer_addresses,
            secondary_signers,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "multi_agent_signature")]
    MultiAgentSignature,
}

impl Default for Type {
    fn default() -> Type {
        Self::MultiAgentSignature
    }
}

