/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionSignatureMultiEd25519Signature {
    /// The public keys for the Ed25519 signature
    #[serde(rename = "public_keys")]
    pub public_keys: Vec<String>,
    /// Signature associated with the public keys in the same order
    #[serde(rename = "signatures")]
    pub signatures: Vec<String>,
    /// The number of signatures required for a successful transaction
    #[serde(rename = "threshold")]
    pub threshold: i32,
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "bitmap")]
    pub bitmap: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl TransactionSignatureMultiEd25519Signature {
    pub fn new(public_keys: Vec<String>, signatures: Vec<String>, threshold: i32, bitmap: String, r#type: Type) -> TransactionSignatureMultiEd25519Signature {
        TransactionSignatureMultiEd25519Signature {
            public_keys,
            signatures,
            threshold,
            bitmap,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "multi_ed25519_signature")]
    MultiEd25519Signature,
}

impl Default for Type {
    fn default() -> Type {
        Self::MultiEd25519Signature
    }
}

