/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionsBatchSingleSubmissionFailure : Information telling which batch submission transactions failed
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionsBatchSingleSubmissionFailure {
    #[serde(rename = "error")]
    pub error: Box<models::AptosError>,
    /// The index of which transaction failed, same as submission order
    #[serde(rename = "transaction_index")]
    pub transaction_index: i32,
}

impl TransactionsBatchSingleSubmissionFailure {
    /// Information telling which batch submission transactions failed
    pub fn new(error: models::AptosError, transaction_index: i32) -> TransactionsBatchSingleSubmissionFailure {
        TransactionsBatchSingleSubmissionFailure {
            error: Box::new(error),
            transaction_index,
        }
    }
}

