/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionPayload : An enum of the possible transaction payloads
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TransactionPayload {
    #[serde(rename = "entry_function_payload")]
    EntryFunctionPayload(Box<models::TransactionPayloadEntryFunctionPayload>),
    #[serde(rename = "script_payload")]
    ScriptPayload(Box<models::TransactionPayloadScriptPayload>),
    #[serde(rename = "module_bundle_payload")]
    ModuleBundlePayload(Box<models::TransactionPayloadDeprecatedModuleBundlePayload>),
    #[serde(rename = "multisig_payload")]
    MultisigPayload(Box<models::TransactionPayloadMultisigPayload>),
}

impl Default for TransactionPayload {
    fn default() -> Self {
        Self::EntryFunctionPayload(Default::default())
    }
}
