/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionPayloadMultisigPayload {
    /// A hex encoded 32 byte Aptos account address.  This is represented in a string as a 64 character hex string, sometimes shortened by stripping leading 0s, and adding a 0x.  For example, address 0x0000000000000000000000000000000000000000000000000000000000000001 is represented as 0x1. 
    #[serde(rename = "multisig_address")]
    pub multisig_address: String,
    #[serde(rename = "transaction_payload", skip_serializing_if = "Option::is_none")]
    pub transaction_payload: Option<Box<models::MultisigTransactionPayload>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl TransactionPayloadMultisigPayload {
    pub fn new(multisig_address: String, r#type: Type) -> TransactionPayloadMultisigPayload {
        TransactionPayloadMultisigPayload {
            multisig_address,
            transaction_payload: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "multisig_payload")]
    MultisigPayload,
}

impl Default for Type {
    fn default() -> Type {
        Self::MultisigPayload
    }
}

