/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnsupportedJwk : Move type `0x1::jwks::UnsupportedJWK` in rust. See its doc in Move for more details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnsupportedJwk {
    #[serde(rename = "id")]
    pub id: Vec<i32>,
    #[serde(rename = "payload")]
    pub payload: Vec<i32>,
}

impl UnsupportedJwk {
    /// Move type `0x1::jwks::UnsupportedJWK` in rust. See its doc in Move for more details.
    pub fn new(id: Vec<i32>, payload: Vec<i32>) -> UnsupportedJwk {
        UnsupportedJwk {
            id,
            payload,
        }
    }
}

