/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WriteSetPayload : A writeset payload, used only for genesis
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WriteSetPayload {
    #[serde(rename = "write_set")]
    pub write_set: Box<models::WriteSet>,
}

impl WriteSetPayload {
    /// A writeset payload, used only for genesis
    pub fn new(write_set: models::WriteSet) -> WriteSetPayload {
        WriteSetPayload {
            write_set: Box::new(write_set),
        }
    }
}

