/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WriteSetChange : A final state change of a transaction on a resource or module
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum WriteSetChange {
    #[serde(rename="delete_module")]
    DeleteModule(Box<models::WriteSetChangeDeleteModule>),
    #[serde(rename="delete_resource")]
    DeleteResource(Box<models::WriteSetChangeDeleteResource>),
    #[serde(rename="delete_table_item")]
    DeleteTableItem(Box<models::WriteSetChangeDeleteTableItem>),
    #[serde(rename="write_module")]
    WriteModule(Box<models::WriteSetChangeWriteModule>),
    #[serde(rename="write_resource")]
    WriteResource(Box<models::WriteSetChangeWriteResource>),
    #[serde(rename="write_table_item")]
    WriteTableItem(Box<models::WriteSetChangeWriteTableItem>),
}

impl Default for WriteSetChange {
    fn default() -> Self {
        Self::DeleteModule(Default::default())
    }
}


