/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WriteSet : The associated writeset with a payload
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum WriteSet {
    #[serde(rename="script_write_set")]
    ScriptWriteSet(Box<models::WriteSetScriptWriteSet>),
    #[serde(rename="direct_write_set")]
    DirectWriteSet(Box<models::WriteSetDirectWriteSet>),
}

impl Default for WriteSet {
    fn default() -> Self {
        Self::ScriptWriteSet(Default::default())
    }
}


