/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WriteSetDirectWriteSet {
    #[serde(rename = "changes")]
    pub changes: Vec<models::WriteSetChange>,
    #[serde(rename = "events")]
    pub events: Vec<models::Event>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl WriteSetDirectWriteSet {
    pub fn new(changes: Vec<models::WriteSetChange>, events: Vec<models::Event>, r#type: Type) -> WriteSetDirectWriteSet {
        WriteSetDirectWriteSet {
            changes,
            events,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "direct_write_set")]
    DirectWriteSet,
}

impl Default for Type {
    fn default() -> Type {
        Self::DirectWriteSet
    }
}

