/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WriteSetChangeWriteTableItem {
    #[serde(rename = "state_key_hash")]
    pub state_key_hash: String,
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "handle")]
    pub handle: String,
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "key")]
    pub key: String,
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::DecodedTableData>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl WriteSetChangeWriteTableItem {
    pub fn new(state_key_hash: String, handle: String, key: String, value: String, r#type: Type) -> WriteSetChangeWriteTableItem {
        WriteSetChangeWriteTableItem {
            state_key_hash,
            handle,
            key,
            value,
            data: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "write_table_item")]
    WriteTableItem,
}

impl Default for Type {
    fn default() -> Type {
        Self::WriteTableItem
    }
}

