/*
 * Aptos Node API
 *
 * The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WriteTableItem : Change set to write a table item
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WriteTableItem {
    #[serde(rename = "state_key_hash")]
    pub state_key_hash: String,
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "handle")]
    pub handle: String,
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "key")]
    pub key: String,
    /// All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with two hex digits per byte.  Unlike the `Address` type, HexEncodedBytes will not trim any zeros. 
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::DecodedTableData>>,
}

impl WriteTableItem {
    /// Change set to write a table item
    pub fn new(state_key_hash: String, handle: String, key: String, value: String) -> WriteTableItem {
        WriteTableItem {
            state_key_hash,
            handle,
            key,
            value,
            data: None,
        }
    }
}

